"""P-3 thread machine — pure conversational logic.

Deliberately free of LangGraph and Pipecat imports so the behaviour that
matters can be unit-tested without a voice pipeline or a graph runtime.
`p3_graph` wires these functions into a graph; `bot.py` wires that graph into
one Pipecat processor.

THE MODEL PROPOSES, CODE DISPOSES.
    Everything here is the "disposes" half: which stage we are in, whether
    advice is permitted, which facts are already known, when to stop asking.
    Every sentence Mira speaks is still generated by the LLM.

A THREAD, NOT THE CONVERSATION.
    The graph governs one topic being worked ("night hunger"). A router above
    it decides per turn whether the turn even belongs to that thread. Turns
    that do not — a factual aside, a joke — take the QUICK lane and the thread
    does not move. That is what stops this feeling like a questionnaire.
"""
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone

import memory_facts

# ---------------------------------------------------------------- lanes ----
LANE_QUICK = "QUICK"        # answer, do not touch the thread
LANE_ADVANCE = "ADVANCE"    # this turn moves the active thread
LANE_SWITCH = "SWITCH"      # park the active thread, open a new one
LANE_RESUME = "RESUME"      # return to a parked thread
LANE_SAFETY = "SAFETY"      # deterministic pre-emption
LANES = (LANE_QUICK, LANE_ADVANCE, LANE_SWITCH, LANE_RESUME, LANE_SAFETY)

# --------------------------------------------------------------- stages ----
S_UNDERSTAND = "UNDERSTAND"
S_GATHER = "GATHER"
S_REFLECT = "REFLECT"
S_ADVISE = "ADVISE"          # REASON and ADVISE merged: one utterance in practice
S_CONFIRM = "CONFIRM"
S_CLOSE = "CLOSE"
STAGE_ORDER = [S_UNDERSTAND, S_GATHER, S_REFLECT, S_ADVISE, S_CONFIRM, S_CLOSE]

# Max turns a stage may occupy before it force-advances. A stage that can loop
# is how a graph starts to feel like a form.
DWELL = {S_UNDERSTAND: 1, S_GATHER: 2, S_REFLECT: 1, S_ADVISE: 1, S_CONFIRM: 1}

# Spoken-word budget per stage, expressed in WORDS rather than tokens: the
# model follows a word count in the directive far more reliably than it
# respects a token ceiling, and max_tokens stays as the hard backstop.
# Replaces one global limit — "haan bilkul" and a causal explanation cannot
# share a ceiling.
BUDGET = {S_UNDERSTAND: 25, S_GATHER: 25, S_REFLECT: 22,
          S_ADVISE: 45, S_CONFIRM: 15, S_CLOSE: 15}
BUDGET_QUICK = 30

MAX_THREADS = 3              # parked-thread cap; oldest spills to open loops
MAX_NEEDED_PATHS = 3         # a plan longer than this guarantees an interrogation

# Which family of fact to ask about first when several are missing. The router
# orders by relevance and that ordering is respected within a family, but
# identity is pushed last on purpose: asking someone's height and weight
# because they said "I feel fat" is the single most tone-deaf thing this
# system can do.
GAP_PRIORITY = {
    "current_pattern": 0, "progress": 1, "diet": 2, "lifestyle": 3,
    "preferences": 4, "goals": 5, "health": 6, "entities": 7,
    "misc": 8, "identity": 9,
}

# ------------------------------------------------------------ staleness ----
# Facts age at very different rates. Resolved by first path segment.
# None = never goes stale.
TTL_DAYS = {
    "identity": None,
    "health": 180,
    "diet": 90,
    "preferences": 90,
    "goals": 90,
    "lifestyle": 60,
    "current_pattern": 28,
    "progress": 14,
    "entities": 30,
    "misc": 90,
}


def _now():
    return datetime.now(timezone.utc)


def _parse_ts(raw):
    if not raw:
        return None
    try:
        return datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
    except (ValueError, TypeError):
        return None


def is_stale(path, valid_from, now=None):
    ttl = TTL_DAYS.get((path or "").split(".")[0])
    if ttl is None:
        return False
    ts = _parse_ts(valid_from)
    if ts is None:
        return True                      # unknown age -> treat as stale
    return (( now or _now()) - ts).days > ttl


# ---------------------------------------------------------------- thread ---
@dataclass
class Thread:
    topic: str
    template: str = "PROBLEM"            # PROBLEM | PLAN | HABIT
    stage: str = S_UNDERSTAND
    stage_turns: int = 0
    needed_paths: list = field(default_factory=list)   # chosen from memory SCHEMA
    adhoc: list = field(default_factory=list)          # thread-only, never a typed fact
    slots: dict = field(default_factory=dict)          # path/adhoc -> value
    asked: list = field(default_factory=list)          # what we have already asked for
    reflected: bool = False
    advice: list = field(default_factory=list)
    parked: bool = False
    opened_at: int = 0

    def gaps(self):
        """Requested things we still do not have a value for."""
        wanted = list(self.needed_paths) + list(self.adhoc)
        return [p for p in wanted if not str(self.slots.get(p, "")).strip()]


# ------------------------------------------------------------- gathering ---
def plan_gather(thread, ledger_view, fact_ages, now=None):
    """Split the thread's requested paths into known / stale / missing.

    ledger_view : projected long-term memory, {"health": {"conditions": [...]}}
    fact_ages   : {path: valid_from_iso} from the ledger

    Pre-fill is the single biggest reason this does not feel like an intake:
    for a returning user most requested paths are already known, and a
    known-but-stale fact is VERIFIED (a yes/no) rather than re-asked openly.
    """
    now = now or _now()
    known, stale, missing = {}, [], []
    for path in thread.needed_paths:
        # 1. Anything the user told us EARLIER IN THIS CALL wins outright. Without
        #    this check a slot the user just answered still reads as missing, and
        #    the GATHER directive asks for it again — the single failure users
        #    notice most ("she isn't listening").
        in_call = thread.slots.get(path)
        if str(in_call or "").strip():
            known[path] = in_call
            continue
        val = _read_path(ledger_view, path)
        if val in (None, "", [], {}):
            missing.append(path)
        elif is_stale(path, fact_ages.get(path), now):
            stale.append(path)
            known[path] = val                 # usable, just worth confirming
        else:
            known[path] = val
    for a in thread.adhoc:                    # ad-hoc is never in the ledger
        if not str(thread.slots.get(a, "")).strip():
            missing.append(a)
    return {"known": known, "stale": stale, "missing": missing}


def _tokens_of(text):
    drop = {"", "current", "pattern", "the", "a", "of", "her", "his", "their",
            "user", "what", "when", "how", "does", "do", "is", "are"}
    return {t for t in re.split(r"[^a-zA-Z0-9]+", str(text).lower()) if t} - drop


# Synonyms for the SCHEMA's leaf names — a small closed set, so this is a
# vocabulary bridge rather than per-problem hardcoding. It lets "dinner_food"
# reach current_pattern.dinner.frequent without the router having to guess our
# exact key names.
_LEAF_SYNONYMS = {
    "frequent": {"food", "foods", "eat", "eats", "eating", "meal", "meals",
                 "items", "dish", "dishes", "khana", "menu", "usually"},
    "time": {"time", "timing", "when", "hour", "clock", "baje", "oclock"},
    "note": {"note", "notes", "detail", "details", "comment"},
    "gaps": {"gap", "gaps", "skip", "skipped", "missed", "missing"},
    "conditions": {"condition", "conditions", "disease", "illness", "diagnosis"},
    "allergies": {"allergy", "allergies", "allergic"},
    "medications": {"medication", "medications", "medicine", "medicines", "drug"},
    "restrictions": {"restriction", "restrictions", "avoid", "avoids", "cannot"},
    "type": {"type", "kind", "vegetarian", "diet"},
    "likes": {"like", "likes", "prefers", "favourite", "favorite"},
    "dislikes": {"dislike", "dislikes", "hates", "hate"},
    "schedule": {"schedule", "routine", "shift", "work", "office", "job"},
    "sleep_time": {"sleep", "sleeps", "sleeping", "bedtime", "sona", "sote",
                   "soti", "sone", "nind", "neend"},
    "cooking_situation": {"cooking", "cook", "cooks", "kitchen"},
    "struggles": {"struggle", "struggles", "difficulty", "hard", "problem"},
    "what_failed": {"failed", "fail", "didnt", "unsuccessful"},
    "what_worked": {"worked", "works", "successful", "helped"},
    "primary_goal": {"goal", "goals", "aim", "objective"},
    "weight_kg": {"weight", "kg", "kilos"},
    "height_cm": {"height", "cm", "tall"},
}

# Leaf words too generic to identify a path on their own — "blood_type" must
# not become diet.type. These always need their qualifier to appear as well.
_GENERIC_LEAVES = {"type", "time", "note", "target", "gaps", "budget",
                   "household", "motivation"}

_TIMEY = re.compile(r"(\d{1,2}\s*(?::|\.)?\s*\d{0,2}\s*(am|pm|बजे|baje)|\d{1,2}\s*(am|pm|बजे|baje))",
                    re.IGNORECASE)


def _expand(tokens):
    """Add leaf names implied by the tokens, so synonyms score like the real name."""
    out = set(tokens)
    for leaf, words in _LEAF_SYNONYMS.items():
        if tokens & words:
            out.add(leaf)
    return out


def map_extracted(raw, thread):
    """Map whatever keys the router invented onto REAL schema paths.

    The router is asked to key its extractions by schema path, but it will not
    always comply — real runs produced keys like "dinner" and "dinner_time".
    Left unmapped, the slot never lands on the path GATHER is waiting for, the
    gap never closes, and Mira asks the same question again. So the mapping is
    done in code, generally, rather than trusting the model to be consistent.

    Returns (mapped, adhoc): mapped is {schema_path: value}, adhoc is
    everything that had no plausible home and is kept on the thread only.
    """
    schema = set(memory_facts.SCHEMA)
    mapped, adhoc = {}, {}
    for key, val in (raw or {}).items():
        k = str(key).strip()
        if not k or not str(val).strip():
            continue
        if k in schema:
            mapped[k] = val
            continue
        kt = _expand(_tokens_of(k))
        if not kt:
            adhoc[k] = val
            continue
        # A bare slot name ("dinner") is ambiguous across .time / .frequent.
        # The VALUE disambiguates: "7pm" is a time, "roti sabzi" is not.
        looks_like_time = bool(_TIMEY.search(str(val)))
        kt = kt | ({"time"} if looks_like_time else {"frequent"}) \
            if kt <= set(memory_facts.MEAL_SLOTS) else kt
        best, score = None, 0.0
        # Prefer paths this thread actually asked for, then the whole schema.
        for pool in (list(thread.needed_paths), sorted(schema)):
            for path in pool:
                pt = _expand(_tokens_of(path))
                if not pt:
                    continue
                sc = len(kt & pt) / len(kt | pt)
                segs = [s for s in path.lower().split(".") if s not in
                        ("current", "pattern")]
                leaf, qualifiers = segs[-1], set(segs[:-1])
                # A key that IS one of the path's segments is a strong signal:
                # "dinner" -> current_pattern.dinner.time
                if kt and kt <= set(segs):
                    sc = max(sc, 0.75)
                # Naming the leaf is strong too ("work_routine" -> schedule).
                # Two-segment paths have unique leaves, so the leaf alone is
                # enough. Deeper paths repeat their leaves across sub-entities
                # (six meal slots all have .time), so there the qualifier must
                # appear too — otherwise "sleep_time" lands on dinner.time.
                needs_qualifier = len(segs) >= 3 or leaf in _GENERIC_LEAVES
                if leaf in kt and (not needs_qualifier or (kt & qualifiers)):
                    sc = max(sc, 0.7)
                if sc > score:
                    best, score = path, sc
            if score >= 0.5:
                break
        if best and score >= 0.5:
            mapped[best] = val
        else:
            adhoc[k] = val
    return mapped, adhoc


def rank_gaps(gaps, needed_order):
    """Most useful missing thing first. Family priority beats router order."""
    order = {p: i for i, p in enumerate(needed_order or [])}
    return sorted(gaps, key=lambda g: (GAP_PRIORITY.get(g.split(".")[0], 7),
                                       order.get(g, 99)))


def _read_path(view, path):
    node = view or {}
    for part in (path or "").split("."):
        if not isinstance(node, dict) or part not in node:
            return None
        node = node[part]
    return node


def prefill(thread, gather):
    """Copy known ledger values into the thread's slots. Never asks."""
    for path, val in (gather.get("known") or {}).items():
        thread.slots.setdefault(path, val)
    return thread


# -------------------------------------------------------------- advance ----
def has_reflectable(gather):
    """Is there anything worth saying back to the user?

    A reflection with nothing in it — "I don't yet know your diet or routine" —
    is worse than no reflection: it spends a turn telling the user we weren't
    listening. Observed live, so REFLECT is now gated on substance.
    """
    return len(gather.get("known") or {}) >= 1


def next_stage(thread, gather, sufficient):
    """Where the thread goes AFTER this turn. Pure function of state.

    `sufficient` is the model's judgement ("can I advise usefully now?") — the
    only place a model opinion enters this module, and code still caps it via
    DWELL. Waiting for every slot is what turns gathering into a form.
    """
    st = thread.stage
    dwelled = thread.stage_turns >= DWELL.get(st, 1)

    if st == S_UNDERSTAND:
        # Skip GATHER when nothing is genuinely missing, or when the user's
        # opening message alone was enough to act on. NOTE: `stale` does NOT
        # force a gather turn — a slightly out-of-date fact is worth confirming
        # inside another sentence, never worth spending a whole turn asking for.
        if sufficient or not gather["missing"]:
            return S_REFLECT if has_reflectable(gather) else S_ADVISE
        return S_GATHER

    if st == S_GATHER:
        if sufficient or not gather["missing"] or dwelled:
            # Force-advanced with nothing learned (two sideways answers, say):
            # skip the reflection and work with what we have rather than
            # narrating our own ignorance back at them.
            return S_REFLECT if has_reflectable(gather) else S_ADVISE
        return S_GATHER

    if st == S_REFLECT:
        return S_ADVISE
    if st == S_ADVISE:
        return S_CONFIRM
    if st == S_CONFIRM:
        return S_CLOSE
    return S_CLOSE


# ------------------------------------------------------------ directives ---
def stage_directive(thread, gather):
    """The behavioural instruction appended to the base system prompt.

    Permissions and budget — never a script. Code decides THAT Mira reflects;
    the model decides HOW. This block is short by design: the personality,
    Hinglish rules and safety framing all live in the base prompt, untouched.
    """
    st = thread.stage
    budget = BUDGET.get(st, 60)

    if st == S_UNDERSTAND:
        d = ("The user has just raised a problem. Ask ONE short question to understand "
             "it better. Do NOT give any advice, tip or solution yet.")
    elif st == S_GATHER:
        # ONE question about ONE thing. The previous version said "cover as much
        # as sounds natural", and the model read that as permission to ask four
        # questions in a row. Naming a single target is the fix.
        ranked = rank_gaps(gather["missing"], thread.needed_paths)
        target = _humanise(ranked[0]) if ranked else "what is still unclear"
        known = ", ".join(f"{_humanise(k)}={v}" for k, v in
                          list(gather["known"].items())[:5])
        d = (f"Ask exactly ONE short, natural question, about ONE thing: {target}. "
             "You may let a closely related detail ride along inside the same "
             "sentence if it sounds natural, but your reply must contain exactly "
             "one question mark and must never read as a list.")
        if known:
            d += (f" You ALREADY know this — never ask for any of it again: {known}.")
        if gather["stale"]:
            d += (f" You also believe {_humanise(gather['stale'][0])} is still true "
                  "but it is a little old; confirm it inside your question rather "
                  "than asking about it separately.")
        d += (" Do not ask for age, height, weight or medical history unless that "
              "is genuinely what you just asked about.")
    elif st == S_REFLECT:
        known = ", ".join(f"{_humanise(k)}={v}" for k, v in
                          list(gather["known"].items())[:5])
        # A bare restatement is a WASTED TURN. Observed live: Mira replied
        # "समझा, तुम 7 pm को दो रोटी+सब्ज़ी dinner लेते हो, फिर 11 pm को सोते हो"
        # and stopped, so the user had to ask "जी, क्या करूं मैं?" to get
        # anywhere. Reflection must always carry the conversation forward.
        d = ("Reflect what they told you back in ONE short clause so they feel "
             "heard, then IMMEDIATELY carry it forward in the same breath — name "
             "what you think is going on. Do NOT simply repeat their words and "
             "stop, and do NOT ask a question in this turn.")
        if known:
            d += f" What you know: {known}."
        # Only hold advice back while the picture is genuinely thin. Two known
        # facts is enough to act on — stretching a clear answer over two turns
        # is the ceremony that makes a graph feel like a graph.
        if len(gather["known"]) >= 2:
            d += (" The picture is clear enough, so give the one concrete "
                  "suggestion in this same reply rather than making them ask for it.")
        if gather["stale"]:
            first = _humanise(gather["stale"][0])
            d += (f" You believe {first} is still true but it is a little old — "
                  f"you may fold a light confirmation into the same sentence.")
    elif st == S_ADVISE:
        # Live log: "policy VIOLATION stage=ADVISE: more than one question".
        # The stage said nothing about question count, so the model stacked
        # three symptom checks into one breath.
        d = ("Name the likely reason and give ONE concrete change. "
             "You MUST refer to something specific about this user — a food, a "
             "timing, a condition — not generic advice. ONE suggestion only, "
             "never a list of options. End with AT MOST one short question, or "
             "no question at all.")
    elif st == S_CONFIRM:
        d = "Briefly check whether that feels doable for them. One short question."
    else:
        d = "Wrap this topic up warmly in one short line."

    d += f" Keep it under {budget} words."
    return {"directive": d, "budget": budget,
            "may_advise": st in (S_ADVISE, S_CLOSE)}


# Stages at which the thread has earned the right to prescribe.
ADVISE_STAGES = (S_ADVISE, S_CONFIRM, S_CLOSE)


def quick_directive(situation="", active=None, explicit_advice_request=False):
    """QUICK lane: answer and get out. The thread does not move.

    THE BYPASS THIS CLOSES. `may_advise` used to be True for every QUICK turn,
    so a single router misclassification handed out advice regardless of thread
    state. Observed live: the user said "हम्म" and received a full diet
    prescription while the fatigue thread was still gathering.

    Permission now comes from the THREAD, not the lane. With no thread open a
    direct question still gets a direct answer — that is P-3's job. With a
    thread open and still short of ADVISE, the question is answered but
    prescribing is withheld, including when the user asks for it outright:
    the stage rules decide when advice is earned, not how loudly it is
    requested.
    """
    gated = bool(active) and not active.parked and active.stage not in ADVISE_STAGES
    d = ("Answer the user's question directly and briefly. "
         "Do not start a consultation and do not interrogate them.")
    if situation == "OFF_TOPIC":
        d = ("Answer briefly and warmly, then steer back to what you were "
             "discussing. Do not lecture about what you can or cannot help with.")
    elif situation == "CORRECTION":
        d = ("The user is correcting you. Accept it immediately and warmly. "
             "Do NOT defend or explain what you said before. Then carry on.")
    elif situation == "MEMORY_QUERY":
        d = "Answer from what you remember about this user. Be specific."

    if gated:
        d += (f" IMPORTANT: you are in the middle of understanding their '{active.topic}' "
              "problem and do not yet know enough to advise on it. Answer only what "
              "they just asked. Do NOT add tips, plans or recommendations about "
              f"'{active.topic}', and do not list foods to eat or avoid.")
        if explicit_advice_request:
            d += (" They are asking for advice, so acknowledge that warmly and say "
                  "you want one more detail first — then ask for it in the same "
                  "breath. Exactly one question.")
        else:
            d += " Then steer back to what you were discussing, without a question."
    d += f" Keep it under {BUDGET_QUICK} words."
    return {"directive": d, "budget": BUDGET_QUICK, "may_advise": not gated}


def _humanise(path):
    return (path or "").replace("current_pattern.", "").replace("_", " ").replace(".", " ")


# ------------------------------------------------------------- validation --
def validate(text, policy, thread=None):
    """Post-generation checks. Returns a list of failures (empty = fine).

    Advisory: used for logging and, at most, one regeneration. Never blocks a
    reply outright — dead air is worse than a slightly long sentence.
    """
    problems = []
    t = (text or "").strip()
    if not t:
        return ["empty"]
    words = len(t.split())
    cap = int(policy.get("budget") or 40)
    if words > cap * 1.6:
        problems.append(f"too long ({words} words, budget {cap})")
    if t.count("?") > 1:
        problems.append("more than one question")
    if not policy.get("may_advise") and thread is not None:
        pass                                    # advice-detection is a judge job, not a regex
    if policy.get("stage") == S_REFLECT and "?" in t:
        problems.append("asked a question during REFLECT")
    return problems


# ------------------------------------------------------- thread stack ------
def find_parked(threads, topic_hint):
    """Best-effort match of a resume request to a parked thread."""
    hint = (topic_hint or "").lower().strip()
    if not hint:
        return None
    for t in threads:
        if not t.parked:
            continue
        if hint in t.topic.lower() or t.topic.lower() in hint:
            return t
    return None


def park_active(threads):
    for t in threads:
        if not t.parked:
            t.parked = True
    return threads


def spill_oldest(threads, limit=MAX_THREADS):
    """Cap the stack. Oldest parked threads spill out as open loops."""
    if len(threads) <= limit:
        return threads, []
    parked = [t for t in threads if t.parked]
    parked.sort(key=lambda t: t.opened_at)
    spill = parked[: len(threads) - limit]
    keep = [t for t in threads if t not in spill]
    return keep, spill


def open_loop_text(thread):
    if thread.advice:
        return f"did {thread.advice[0]} help with {thread.topic}?"
    return f"follow up on {thread.topic}"
