"""P-3 thread machine — pure conversational logic.

Deliberately free of LangGraph and Pipecat imports so the behaviour that
matters can be unit-tested without a voice pipeline or a graph runtime.
`p3_graph` wires these functions into a graph; `bot.py` wires that graph into
one Pipecat processor.

THE MODEL PROPOSES, CODE DISPOSES.
    Everything here is the "disposes" half: which stage we are in, whether
    advice is permitted, which facts are already known, when to stop asking.
    Every sentence Mira speaks is still generated by the LLM.

A THREAD, NOT THE CONVERSATION.
    The graph governs one topic being worked ("night hunger"). A router above
    it decides per turn whether the turn even belongs to that thread. Turns
    that do not — a factual aside, a joke — take the QUICK lane and the thread
    does not move. That is what stops this feeling like a questionnaire.
"""
from dataclasses import dataclass, field
from datetime import datetime, timezone

# ---------------------------------------------------------------- lanes ----
LANE_QUICK = "QUICK"        # answer, do not touch the thread
LANE_ADVANCE = "ADVANCE"    # this turn moves the active thread
LANE_SWITCH = "SWITCH"      # park the active thread, open a new one
LANE_RESUME = "RESUME"      # return to a parked thread
LANE_SAFETY = "SAFETY"      # deterministic pre-emption
LANES = (LANE_QUICK, LANE_ADVANCE, LANE_SWITCH, LANE_RESUME, LANE_SAFETY)

# --------------------------------------------------------------- stages ----
S_UNDERSTAND = "UNDERSTAND"
S_GATHER = "GATHER"
S_REFLECT = "REFLECT"
S_ADVISE = "ADVISE"          # REASON and ADVISE merged: one utterance in practice
S_CONFIRM = "CONFIRM"
S_CLOSE = "CLOSE"
STAGE_ORDER = [S_UNDERSTAND, S_GATHER, S_REFLECT, S_ADVISE, S_CONFIRM, S_CLOSE]

# Max turns a stage may occupy before it force-advances. A stage that can loop
# is how a graph starts to feel like a form.
DWELL = {S_UNDERSTAND: 1, S_GATHER: 2, S_REFLECT: 1, S_ADVISE: 1, S_CONFIRM: 1}

# Spoken-word budget per stage, expressed in WORDS rather than tokens: the
# model follows a word count in the directive far more reliably than it
# respects a token ceiling, and max_tokens stays as the hard backstop.
# Replaces one global limit — "haan bilkul" and a causal explanation cannot
# share a ceiling.
BUDGET = {S_UNDERSTAND: 25, S_GATHER: 25, S_REFLECT: 22,
          S_ADVISE: 45, S_CONFIRM: 15, S_CLOSE: 15}
BUDGET_QUICK = 30

MAX_THREADS = 3              # parked-thread cap; oldest spills to open loops

# ------------------------------------------------------------ staleness ----
# Facts age at very different rates. Resolved by first path segment.
# None = never goes stale.
TTL_DAYS = {
    "identity": None,
    "health": 180,
    "diet": 90,
    "preferences": 90,
    "goals": 90,
    "lifestyle": 60,
    "current_pattern": 28,
    "progress": 14,
    "entities": 30,
    "misc": 90,
}


def _now():
    return datetime.now(timezone.utc)


def _parse_ts(raw):
    if not raw:
        return None
    try:
        return datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
    except (ValueError, TypeError):
        return None


def is_stale(path, valid_from, now=None):
    ttl = TTL_DAYS.get((path or "").split(".")[0])
    if ttl is None:
        return False
    ts = _parse_ts(valid_from)
    if ts is None:
        return True                      # unknown age -> treat as stale
    return (( now or _now()) - ts).days > ttl


# ---------------------------------------------------------------- thread ---
@dataclass
class Thread:
    topic: str
    template: str = "PROBLEM"            # PROBLEM | PLAN | HABIT
    stage: str = S_UNDERSTAND
    stage_turns: int = 0
    needed_paths: list = field(default_factory=list)   # chosen from memory SCHEMA
    adhoc: list = field(default_factory=list)          # thread-only, never a typed fact
    slots: dict = field(default_factory=dict)          # path/adhoc -> value
    asked: list = field(default_factory=list)          # what we have already asked for
    reflected: bool = False
    advice: list = field(default_factory=list)
    parked: bool = False
    opened_at: int = 0

    def gaps(self):
        """Requested things we still do not have a value for."""
        wanted = list(self.needed_paths) + list(self.adhoc)
        return [p for p in wanted if not str(self.slots.get(p, "")).strip()]


# ------------------------------------------------------------- gathering ---
def plan_gather(thread, ledger_view, fact_ages, now=None):
    """Split the thread's requested paths into known / stale / missing.

    ledger_view : projected long-term memory, {"health": {"conditions": [...]}}
    fact_ages   : {path: valid_from_iso} from the ledger

    Pre-fill is the single biggest reason this does not feel like an intake:
    for a returning user most requested paths are already known, and a
    known-but-stale fact is VERIFIED (a yes/no) rather than re-asked openly.
    """
    now = now or _now()
    known, stale, missing = {}, [], []
    for path in thread.needed_paths:
        # 1. Anything the user told us EARLIER IN THIS CALL wins outright. Without
        #    this check a slot the user just answered still reads as missing, and
        #    the GATHER directive asks for it again — the single failure users
        #    notice most ("she isn't listening").
        in_call = thread.slots.get(path)
        if str(in_call or "").strip():
            known[path] = in_call
            continue
        val = _read_path(ledger_view, path)
        if val in (None, "", [], {}):
            missing.append(path)
        elif is_stale(path, fact_ages.get(path), now):
            stale.append(path)
            known[path] = val                 # usable, just worth confirming
        else:
            known[path] = val
    for a in thread.adhoc:                    # ad-hoc is never in the ledger
        if not str(thread.slots.get(a, "")).strip():
            missing.append(a)
    return {"known": known, "stale": stale, "missing": missing}


def _read_path(view, path):
    node = view or {}
    for part in (path or "").split("."):
        if not isinstance(node, dict) or part not in node:
            return None
        node = node[part]
    return node


def prefill(thread, gather):
    """Copy known ledger values into the thread's slots. Never asks."""
    for path, val in (gather.get("known") or {}).items():
        thread.slots.setdefault(path, val)
    return thread


# -------------------------------------------------------------- advance ----
def next_stage(thread, gather, sufficient):
    """Where the thread goes AFTER this turn. Pure function of state.

    `sufficient` is the model's judgement ("can I advise usefully now?") — the
    only place a model opinion enters this module, and code still caps it via
    DWELL. Waiting for every slot is what turns gathering into a form.
    """
    st = thread.stage
    dwelled = thread.stage_turns >= DWELL.get(st, 1)

    if st == S_UNDERSTAND:
        # Skip GATHER when nothing is genuinely missing, or when the user's
        # opening message alone was enough to act on. NOTE: `stale` does NOT
        # force a gather turn — a slightly out-of-date fact is worth confirming
        # inside another sentence, never worth spending a whole turn asking for.
        if sufficient or not gather["missing"]:
            return S_REFLECT
        return S_GATHER

    if st == S_GATHER:
        if sufficient or not gather["missing"] or dwelled:
            return S_REFLECT
        return S_GATHER

    if st == S_REFLECT:
        return S_ADVISE
    if st == S_ADVISE:
        return S_CONFIRM
    if st == S_CONFIRM:
        return S_CLOSE
    return S_CLOSE


# ------------------------------------------------------------ directives ---
def stage_directive(thread, gather):
    """The behavioural instruction appended to the base system prompt.

    Permissions and budget — never a script. Code decides THAT Mira reflects;
    the model decides HOW. This block is short by design: the personality,
    Hinglish rules and safety framing all live in the base prompt, untouched.
    """
    st = thread.stage
    budget = BUDGET.get(st, 60)

    if st == S_UNDERSTAND:
        d = ("The user has just raised a problem. Ask ONE short question to understand "
             "it better. Do NOT give any advice, tip or solution yet.")
    elif st == S_GATHER:
        gaps = gather["missing"] + gather["stale"]
        pretty = ", ".join(_humanise(g) for g in gaps[:4]) or "what you still need"
        known = ", ".join(f"{_humanise(k)}={v}" for k, v in
                          list(gather["known"].items())[:4])
        d = (f"You still need: {pretty}. Ask ONE natural question — cover as much of "
             f"that as sounds natural in a single question, do not ask them one by one.")
        if gather["stale"]:
            d += (" Some of it you already believe you know but it may be out of date — "
                  "confirm those as a quick yes/no rather than asking openly.")
        if known:
            d += f" Already known, do NOT ask again: {known}."
    elif st == S_REFLECT:
        known = ", ".join(f"{_humanise(k)}={v}" for k, v in
                          list(gather["known"].items())[:5])
        d = ("Say the problem back in your own words so they feel heard. "
             "Do NOT ask a question and do NOT advise in this turn.")
        if known:
            d += f" Use what you know: {known}."
        if gather["stale"]:
            first = _humanise(gather["stale"][0])
            d += (f" You believe {first} is still true but it is a little old — "
                  f"you may fold a light confirmation into the same sentence.")
    elif st == S_ADVISE:
        d = ("Now name the likely reason and give ONE concrete change. "
             "You MUST refer to something specific about this user — a food, a timing, "
             "a condition — not generic advice.")
    elif st == S_CONFIRM:
        d = "Briefly check whether that feels doable for them. One short question."
    else:
        d = "Wrap this topic up warmly in one short line."

    d += f" Keep it under {budget} words."
    return {"directive": d, "budget": budget,
            "may_advise": st in (S_ADVISE, S_CLOSE)}


def quick_directive(situation=""):
    """QUICK lane: answer and get out. The thread does not move."""
    d = ("Answer the user's question directly and briefly. "
         "Do not start a consultation and do not interrogate them.")
    if situation == "OFF_TOPIC":
        d = ("Answer briefly and warmly, then steer back to what you were "
             "discussing. Do not lecture about what you can or cannot help with.")
    elif situation == "CORRECTION":
        d = ("The user is correcting you. Accept it immediately and warmly. "
             "Do NOT defend or explain what you said before. Then carry on.")
    elif situation == "MEMORY_QUERY":
        d = "Answer from what you remember about this user. Be specific."
    d += f" Keep it under {BUDGET_QUICK} words."
    return {"directive": d, "budget": BUDGET_QUICK, "may_advise": True}


def _humanise(path):
    return (path or "").replace("current_pattern.", "").replace("_", " ").replace(".", " ")


# ------------------------------------------------------------- validation --
def validate(text, policy, thread=None):
    """Post-generation checks. Returns a list of failures (empty = fine).

    Advisory: used for logging and, at most, one regeneration. Never blocks a
    reply outright — dead air is worse than a slightly long sentence.
    """
    problems = []
    t = (text or "").strip()
    if not t:
        return ["empty"]
    words = len(t.split())
    cap = int(policy.get("budget") or 40)
    if words > cap * 1.6:
        problems.append(f"too long ({words} words, budget {cap})")
    if t.count("?") > 1:
        problems.append("more than one question")
    if not policy.get("may_advise") and thread is not None:
        pass                                    # advice-detection is a judge job, not a regex
    if policy.get("stage") == S_REFLECT and "?" in t:
        problems.append("asked a question during REFLECT")
    return problems


# ------------------------------------------------------- thread stack ------
def find_parked(threads, topic_hint):
    """Best-effort match of a resume request to a parked thread."""
    hint = (topic_hint or "").lower().strip()
    if not hint:
        return None
    for t in threads:
        if not t.parked:
            continue
        if hint in t.topic.lower() or t.topic.lower() in hint:
            return t
    return None


def park_active(threads):
    for t in threads:
        if not t.parked:
            t.parked = True
    return threads


def spill_oldest(threads, limit=MAX_THREADS):
    """Cap the stack. Oldest parked threads spill out as open loops."""
    if len(threads) <= limit:
        return threads, []
    parked = [t for t in threads if t.parked]
    parked.sort(key=lambda t: t.opened_at)
    spill = parked[: len(threads) - limit]
    keep = [t for t in threads if t not in spill]
    return keep, spill


def open_loop_text(thread):
    if thread.advice:
        return f"did {thread.advice[0]} help with {thread.topic}?"
    return f"follow up on {thread.topic}"
